global.questions = ds_list_create();
var a;
a[0] = "Question 1";
a[1] = "Answer 1";
a[2] = "Answer 2";
a[3] = "Answer 3";
a[4] = "Answer 4";
a[5] = 4 /* correct answer */;
ds_list_add(global.questions, a);
a = 0;
a[0] = "Question 2";
a[1] = "Answer 1";
a[2] = "Answer 2";
a[3] = "Answer 3";
a[4] = "Answer 4";
a[5] = 2 /* correct answer */;
ds_list_add(global.questions, a);
a = 0;

ds_list_shuffle(global.questions);
