global.questions_p2 = ds_list_create();
var a;
a[0] = "1 + 1 = ?";
a[1] = "1";
a[2] = "11";
a[3] = "3";
a[4] = "2";
a[5] = 4 /* correct answer */;
ds_list_add(global.questions_p2, a);
a = 0;
a[0] = "1 + 2 = ?";
a[1] = "12";
a[2] = "3";
a[3] = "4";
a[4] = "2";
a[5] = 2 /* correct answer */;
ds_list_add(global.questions_p2, a);
a = 0;
a[0] = "2 + 2 = ?";
a[1] = "Y";
a[2] = "X";
a[3] = "4";
a[4] = "A";
a[5] = 3 /* correct answer */;
ds_list_add(global.questions_p2, a);
a = 0;
a[0] = "2 + 1 = ?";
a[1] = "Y";
a[2] = "X";
a[3] = "3";
a[4] = "A";
a[5] = 3 /* correct answer */;
ds_list_add(global.questions_p2, a);
a = 0;
a[0] = "2 + 3 = ?";
a[1] = "Y";
a[2] = "X";
a[3] = "5";
a[4] = "A";
a[5] = 3 /* correct answer */;
ds_list_add(global.questions_p2, a);
a = 0;
